config/routes.rb
Rails.application.routes.draw do
  resources :resource_links, except: %i[show index]

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'
  
  resources :users, except: %i[index destroy create new] do
    get :update_password, on: :member
    post :change_password, on: :member
  end
  resources :todo_items, except: %i[index show edit update] do
    post :flip, on: :member
  end
  resources :entries, except: %i[index show]
  resources :projects do
    get :details, on: :member
    get :upload_file_asset, on: :member
    post :create_file_asset, on: :member
    delete :destroy_file_asset, on: :member
    get :download_file_asset, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "application#index"
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :project

  validates :text, presence: true
  validates :project, presence: true

  def flip!
    return check! if !checked?
    return uncheck! if checked?
  end

  def check!
    update_attribute :checked, true
  end

  def uncheck!
    update_attribute :checked, false
  end

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :authorize_user!
  before_action :set_todo_item, only: %i[ flip destroy ]

  def flip
    @todo_item.flip!
    @project = @todo_item.project
    respond_to do |format|
      format.html { redirect_to @project }
      format.json { render :show, status: :created, location: @todo_item }
    end
  end

  # POST /todo_items or /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)
    @project = @todo_item.project
    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @project, notice: "Todo item was successfully created." }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { redirect_to @project, alert: "Invalid" }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1 or /todo_items/1.json
  def destroy
    @project = @todo_item.project
    @todo_item.destroy!

    respond_to do |format|
      format.html { redirect_to @project, notice: "Todo item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_item_params
      params.require(:todo_item).permit(:project_id, :text, :checked)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.haml
.mb-2
  = form_with(model: todo_item, class: 'row') do |form|
    = form.hidden_field :project_id
    .col
      = form.text_field :text, :class => 'form-control', placeholder: 'Add item ...'
    .col-2
      = form.submit 'Add', :class => 'btn btn-outline-primary'

app/views/todo_items/edit.html.haml
%h1 Editing todo_item

= render 'form'

= link_to 'Show', @todo_item
\|
= link_to 'Back', todo_items_path

app/views/todo_items/index.html.haml
%h1 Listing todo_items

%table
  %thead
    %tr
      %th Project
      %th Text
      %th Checked
      %th
      %th
      %th

  %tbody
    - @todo_items.each do |todo_item|
      %tr
        %td= todo_item.project_id
        %td= todo_item.text
        %td= todo_item.checked
        %td= link_to 'Show', todo_item
        %td= link_to 'Edit', edit_todo_item_path(todo_item)
        %td= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Todo item', new_todo_item_path

app/views/todo_items/new.html.haml
%h1 New todo_item

= render 'form'

= link_to 'Back', todo_items_path

app/views/todo_items/show.html.haml
%p#notice= notice

%p
  %b Project:
  = @todo_item.project_id
%p
  %b Text:
  = @todo_item.text
%p
  %b Checked:
  = @todo_item.checked

= link_to 'Edit', edit_todo_item_path(@todo_item)
\|
= link_to 'Back', todo_items_path