config/routes.rb
Rails.application.routes.draw do
  resources :resource_links, except: %i[show index]

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'
  
  resources :users, except: %i[index destroy create new] do
    get :update_password, on: :member
    post :change_password, on: :member
  end
  resources :todo_items, except: %i[index show edit update] do
    post :flip, on: :member
  end
  resources :entries, except: %i[index show]
  resources :projects do
    get :details, on: :member
    get :upload_file_asset, on: :member
    post :create_file_asset, on: :member
    delete :destroy_file_asset, on: :member
    get :download_file_asset, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "application#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: true

  has_many :projects

  validates :email, presence: true, uniqueness: true

  attr_accessor :old_password, :new_password, :new_password_confirmation

  def update_password
    unless authenticate(old_password)
      errors.add :old_password, 'is invalid'
    end

    if new_password_confirmation.blank?
      errors.add :new_password_confirmation, 'does not match'
    end
    
    unless new_password == new_password_confirmation
      errors.add :new_password_confirmation, 'does not match'
    end

    return false if errors.any?

    update(password: new_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user!
  before_action :set_user, only: %i[ show edit update update_password change_password ]

  def update_password
  end

  def change_password
    @user.old_password = params[:user][:old_password]
    @user.new_password = params[:user][:new_password]
    @user.new_password_confirmation = params[:user][:new_password_confirmation]
    if @user.update_password
      redirect_to @user, notice: 'Password updated'
    else
      render :update_password, status: :unprocessable_entity
    end
  end
  
  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :old_password, :new_password, :new_password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_with(model: user) do |form|
  - if user.errors.any?
    = render partial: 'shared/validation_errors_alert', locals: { record: user }

  .mb-3
    = form.label :name, :class => 'form-label'
    = form.text_field :name, :class => 'form-control'
  .mb-3
    = form.submit 'Save', :class => 'btn btn-outline-primary'

app/views/users/edit.html.haml
.container
  %h3.border-bottom Edit Profile
  = render "form", user: current_user

app/views/users/show.html.haml
.border-bottom.fs-5.text-secondary.fst-italic.my-2  This is you
%table.table.mb-5
  %tbody
    %tr
      %td= current_user.id
      %td= current_user.email
      %td= current_user.admin? ? 'Admin' : 'User'
      %td= current_user.name
      %td
        Created
        = time_ago_in_words(current_user.created_at)
        ago
      %td
        Modified
        = time_ago_in_words(current_user.updated_at)
        ago

= link_to 'Update', edit_user_path(current_user), :class => 'btn btn-primary'
= link_to 'Change Password', update_password_user_path(current_user), :class => 'btn btn-primary'

app/views/users/update_password.html.haml
.container
  .col-4.mx-auto
    %h3.border-bottom
      Update Password
    = form_with(model: current_user, url: change_password_user_path(current_user), method: :post) do |form|
      - if current_user.errors.any?
        = render partial: 'shared/validation_errors_alert', locals: { record: current_user }

      .mb-3
        = form.label :old_password, :class => 'form-label'
        = form.password_field :old_password, :class => 'form-control'
      .mb-3
        = form.label :new_password, :class => 'form-label'
        = form.password_field :new_password, :class => 'form-control'
      .mb-3
        = form.label :new_password_confirmation, :class => 'form-label'
        = form.password_field :new_password_confirmation, :class => 'form-control'

      .mb-3
        = form.submit 'Save', :class => 'btn btn-outline-primary'