config/routes.rb
Rails.application.routes.draw do
  resources :resource_links, except: %i[show index]

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'
  
  resources :users, except: %i[index destroy create new] do
    get :update_password, on: :member
    post :change_password, on: :member
  end
  resources :todo_items, except: %i[index show edit update] do
    post :flip, on: :member
  end
  resources :entries, except: %i[index show]
  resources :projects do
    get :details, on: :member
    get :upload_file_asset, on: :member
    post :create_file_asset, on: :member
    delete :destroy_file_asset, on: :member
    get :download_file_asset, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "application#index"
end

app/models/project.rb
class Project < ApplicationRecord
  include Statuses

  has_rich_text :description
  has_many_attached :file_assets
  
  has_many :entries
  has_many :todo_items
  has_many :resource_links
  belongs_to :user

  scope :open, -> { where(status: [:pending, :booting, :ongoing, :paused, :blocked]) }
  scope :closed, -> { where(status: [:finished, :closed, :abandonded]) }

  validates :name, presence: true
  validates :description, presence: true

  def set_locked
    locked = true
    locked_at = Time.now
  end

  def set_locked!
    set_locked
    save
  end

  def refresh_status_from_entries!
    return status if entries.empty?

    last_entry = entries.order('date DESC').first
    return status if last_entry.status == status

    update_attribute :status, last_entry.status
    status
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_user!
  before_action :set_project, only: %i[ show edit update destroy details upload_file_asset create_file_asset destroy_file_asset download_file_asset]

  def download_file_asset
    file_asset = @project.file_assets.where(id: params[:file_asset_id]).take
    if file_asset
      blob = file_asset.blob
      send_data blob.download, filename: blob.filename.to_s, content_type: blob.content_type
    else
      redirect_to details_project_path(@project), alert: 'File asset not found'
      return
    end
  end

  def destroy_file_asset
    file_asset = @project.file_assets.where(id: params[:file_asset_id]).take
    if file_asset
      file_asset.destroy
      redirect_to details_project_path(@project), notice: 'File asset destroyed'
    else
      redirect_to details_project_path(@project), alert: 'File asset not found'
      return
    end
  end
  
  def upload_file_asset
  end

  def create_file_asset
    if params.dig(:project, :file_asset).blank?
      redirect_to details_project_path(@project)
      return
    end
    @project.file_assets.attach params[:project][:file_asset]
    redirect_to details_project_path(@project), notice: 'File asset created'
  end

  def details
  end

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @entries = @project.entries.order('date DESC').page(params[:page])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :status, :locked, :locked_at, :file_asset)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_last_updated_at(project)
    return '<i>No entries</i>'.html_safe unless project.entries.any?

    "Updated #{time_ago_in_words(project.entries.last.created_at)} ago"
  end

  def project_edited_at(project)
    "Edited #{time_ago_in_words(project.updated_at)} ago"
  end

  def project_created_at(project)
    "Created #{time_ago_in_words(project.created_at)} ago"
  end
end

app/views/projects/_file_asset_icon.html.haml
- if content_type =~ /image/i
  = icon('fa-regular', 'file-image')
- elsif content_type =~ /text/i
  = icon('fa-regular', 'file-lines')
- elsif content_type =~ /zip|rar|7zip|tar|gz|7z/i
  = icon('fa-regular', 'file-zipper')
- else
  = icon('fa-regular', 'file')

app/views/projects/_form.html.haml
= form_with(model: project) do |form|
  - if project.errors.any?
    = render partial: 'shared/validation_errors_alert', locals: { record: project }

  .mb-3
    = form.label :name, :class => 'form-label'
    = form.text_field :name, :class => 'form-control'
  .mb-3
    = form.label :description, :class => 'form-label'
    = form.rich_text_area :description, :class => 'form-control'
  .mb-3
    = form.submit 'Save Project', :class => 'btn btn-outline-primary'

app/views/projects/_project.html.haml
%div{:id => "#{dom_id project}"}
  %p
    %strong Name:
    = project.name
  %p
    %strong Description:
    = project.description
  %p
    %strong Status:
    = project.status
  %p
    %strong Locked:
    = project.locked
  %p
    %strong Locked at:
    = project.locked_at

app/views/projects/_status_badge.html.haml
- if record.status_pending?
  %span.badge.rounded-pill.text-bg-primary= record.status.upcase
- elsif record.status_booting?
  %span.badge.rounded-pill.text-bg-success= record.status.upcase
- elsif record.status_ongoing?
  %span.badge.rounded-pill.text-bg-success= record.status.upcase
- elsif record.status_paused?
  %span.badge.rounded-pill.text-bg-warning= record.status.upcase
- elsif record.status_blocked?
  %span.badge.rounded-pill.text-bg-danger= record.status.upcase
- elsif record.status_finished?
  %span.badge.rounded-pill.text-bg-success= record.status.upcase
- elsif record.status_closed?
  %span.badge.rounded-pill.text-bg-danger= record.status.upcase
- elsif record.status_abandoned?
  %span.badge.rounded-pill.text-bg-danger= record.status.upcase

app/views/projects/details.html.haml
.container{style: 'font-size: 0.8em'}
  .row.border-bottom.pb-1
    .col.border-end
      .text-secondary.fst-italic Project Details
    .col.border-end
      .text-secondary.fst-italic= "Created #{time_ago_in_words(@project.created_at)} ago"
    .col.border-end
      .text-secondary.fst-italic= "Updated #{time_ago_in_words(@project.updated_at)} ago"
    .col.border-end
      .text-secondary.fst-italic= "Entries: #{@project.entries.count}"
    .col
      .text-secondary.fst-italic= "By: #{@project.user.name || @project.user.email}"

  .row.pt-1
    .col
      %h3
        = link_to icon('fa-solid', 'arrow-left'), @project
        = @project.name
    .col.text-end
      .mt-2= render partial: 'status_badge', locals: { record: @project }

.container.border
  .trix-content= @project.description

.container.mt-5
  %h3.border-bottom
    Assets
    = link_to icon('fa-solid', 'plus'), upload_file_asset_project_path(@project), class: 'btn btn-sm btn-outline-primary', title: 'New Asset'

  - if @project.file_assets.empty?
    .text-body-secondary.fst-italic No assets yet    
  - @project.file_assets.each do |file_asset|
    .border-bottom.d-inline-block.w-100.pb-2
      .float-start
        .p-3.fs-3.d-inline= render partial: 'file_asset_icon', locals: { content_type: file_asset.blob.content_type }
      .float-start
        %div= file_asset.blob.filename
        .fw-light.text-body-secondary{style: 'font-size: 0.8em'}= file_asset.blob.content_type
      .float-end
        .float-end.ms-1= button_to icon('fa-regular', 'trash-can'), destroy_file_asset_project_path(@project, file_asset_id: file_asset.id), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-sm btn-outline-danger', title: 'Delete'
        .float-end= link_to icon('fa-solid', 'download'), download_file_asset_project_path(@project, file_asset_id: file_asset.id), class: 'btn btn-sm btn-outline-primary', title: 'Download', target: '_blank'


.container.mt-5
  %h3.border-bottom
    Resources
    = link_to icon('fa-solid', 'plus'), new_resource_link_path(project_id: @project.id), class: 'btn btn-sm btn-outline-primary', title: 'New Link'
  - if @project.resource_links.empty?
    .text-body-secondary.fst-italic No links yet
  - @project.resource_links.each do |link|
    .border-bottom.d-inline-block.w-100.pb-2
      .float-start
        .p-3.fs-3.d-inline= icon('fa-solid', 'link')
      .float-start
        %div= link.title
        .fw-light.text-body-secondary{style: 'font-size: 0.8em'}= link_to link.link, link.link, target: '_blank'
      .float-end
        .float-end.ms-1= button_to icon('fa-regular', 'trash-can'), link, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-sm btn-outline-danger', title: 'Delete'
        .float-end= link_to icon('fa-solid', 'pencil'), edit_resource_link_path(link), class: 'btn btn-sm btn-outline-primary', title: 'Edit'

app/views/projects/edit.html.haml
.container
  %h3.border-bottom Edit Project
  = render "form", project: @project

app/views/projects/index.html.haml
%p{:style => "color: green"}= notice
%h1 Projects
#projects
  - @projects.each do |project|
    = render project
    %p
      = link_to "Show this project", project
= link_to "New project", new_project_path

app/views/projects/new.html.haml
.container
  %h3.border-bottom New Project
  = render "form", project: @project

app/views/projects/show.html.haml
.container-fluid.border-bottom.px-0
  .row
    .col
      %h3
        = @project.name
    .col.text-end
      = render partial: 'status_badge', locals: { record: @project }
      = link_to icon('fa-solid', 'pencil'), edit_project_path(@project), class: 'btn btn-sm btn-outline-primary', title: 'Edit'
      = link_to icon('fa-solid', 'magnifying-glass'), details_project_path(@project), class: 'btn btn-sm btn-outline-primary', title: 'Details'
      -# - if @project.locked?
      -#   = link_to icon('fa-solid', 'unlock'), '#', class: 'btn btn-sm btn-outline-danger', title: 'Unlock'
      -# - else
      -#   = link_to icon('fa-solid', 'lock'), '#', class: 'btn btn-sm btn-outline-danger', title: 'Lock'

.container-fluid.px-0.mt-5
  .row
    .col.border-end
      %h4
        Entries
        = link_to icon('fa-solid', 'plus'), new_entry_path(project_id: @project.id), class: 'btn btn-sm btn-outline-primary', title: 'New Entry'
      - if @entries.empty?
        .container.fst-italic No entries yet
      - @entries.each do |entry|
        .container.mb-4
          .fs-4.border-bottom.pb-1
            .row
              .col
                = entry.date
                - unless entry.hours.blank?
                  .badge.text-bg-secondary= "#{entry.hours} h"
                - if entry.status_pending?
                  .badge.text-bg-primary= entry.status.upcase
                - elsif entry.status_booting? || entry.status_ongoing? || entry.status_finished?
                  .badge.text-bg-success= entry.status.upcase
                - elsif entry.status_paused?
                  .badge.text-bg-warning= entry.status.upcase
                - elsif entry.status_blocked? || entry.status_closed? || entry.status_abandoned?
                  .badge.text-bg-danger= entry.status.upcase
              .col.text-end
                = link_to icon('fa-solid', 'pencil'), edit_entry_path(entry), class: 'btn btn-sm btn-outline-primary', title: 'Edit'
                .d-inline-block.float-end.mx-1= button_to icon('fa-regular', 'trash-can'), entry, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'btn btn-sm btn-outline-danger', title: 'Delete'

          .border-bottom
            .trix-content= entry.body
      .entry-pages
        = paginate @entries

    .col-4
      %h4 TODO Overview
      = render partial: 'todo_items/form', locals: { todo_item: TodoItem.new(project_id: @project.id) }
      %hr
      - if @project.todo_items.empty?
        .container.fst-italic Nothing to do yet :p
      - else
        %ul.list-group.list-group-flush.fs-6
          - @project.todo_items.order('created_at ASC').each do |item|
            %li.list-group-item.px-0
              - if item.checked?
                %span.me-2
                  = link_to icon('fa-regular', 'square-check'), flip_todo_item_path(item), data: { turbo_method: :post }
                %span.text-secondary.text-decoration-line-through= item.text
              - else
                %span.me-2
                  = link_to icon('fa-regular', 'square'), flip_todo_item_path(item), data: { turbo_method: :post }
                %span= item.text
              %span.d-inline-block.float-end.mx-1= button_to icon('fa-regular', 'trash-can'), item, method: :delete, class: 'btn btn-sm btn-outline-danger', title: 'Delete'

app/views/projects/upload_file_asset.html.haml
.container
  %h3.border-bottom
    New File Asset for
    = @project.name
  = form_with(model: @project, url: create_file_asset_project_path(@project), method: :post) do |form|
    - if @project.errors.any?
      = render partial: 'shared/validation_errors_alert', locals: { record: @project }

    .mb-3
      = form.label :file_asset, :class => 'form-label'
      = form.file_field :file_asset, :class => 'form-control'
    .mb-3
      = form.submit 'Save File Asset', :class => 'btn btn-outline-primary'