config/routes.rb
Rails.application.routes.draw do
  resources :resource_links, except: %i[show index]

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy'
  
  resources :users, except: %i[index destroy create new] do
    get :update_password, on: :member
    post :change_password, on: :member
  end
  resources :todo_items, except: %i[index show edit update] do
    post :flip, on: :member
  end
  resources :entries, except: %i[index show]
  resources :projects do
    get :details, on: :member
    get :upload_file_asset, on: :member
    post :create_file_asset, on: :member
    delete :destroy_file_asset, on: :member
    get :download_file_asset, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "application#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :authorize_user!, only: [:index]
  
  def index
  end

  private

  def current_user
    @current_user ||= session[:user_id] && User.where(id: session[:user_id]).take
  end

  def authorize_user!
    unless current_user
      redirect_to login_path, alert: 'You need to login'
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.haml
- if flash[:notice]
  .alert.alert-success.rounded-0.text-center.py-1{role: 'alert'}
    = flash[:notice]

- if flash[:alert]
  .alert.alert-warning.rounded-0.text-center.py-1{role: 'alert'}
    = flash[:alert]

app/views/application/_nav_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  .container-fluid
    %a.navbar-brand{ href: root_path }
      = image_tag 'favicon_250x250.png', alt: 'Project Logger', width: 30, height: 30
    %button.navbar-toggler{"aria-controls" => "navbarTogglerDemo02", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarToggler", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarToggler.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        // Nothing to put here yet
        - if current_user
        - else

      %form
        - if current_user
          = link_to 'Create Project', new_project_path, :class => 'btn btn-sm btn-outline-primary mr-2'
          = link_to 'Me', user_path(current_user), :class => 'btn btn-sm btn-outline-primary mr-2'
          = link_to 'Logout', login_path, :class => 'btn btn-sm btn-outline-danger mr-2', :data => { turbo_method: :delete }
        - else
          = link_to 'Login', login_path, :class => 'btn btn-sm btn-outline-primary mr-2'

app/views/application/index.html.haml
.border-bottom.fs-5.text-secondary.fst-italic.my-2  Open Projects
%table.table.mb-5
  %tbody
    - if current_user.projects.empty?
      %i No projects yet
    - current_user.projects.open.order('updated_at DESC').each do |project|
      %tr
        %td= project.id
        %td= project.name
        %td= render partial: 'projects/status_badge', locals: { record: project }
        %td= project_last_updated_at(project)
        %td= project_edited_at(project)
        %td= project_created_at(project)
        %td
          = link_to 'Open', project_path(project), class: 'btn btn-primary btn-sm float-end'

.border-bottom.fs-5.text-secondary.fst-italic.my-2  Closed Projects
%table.table
  %tbody
    - if current_user.projects.empty?
      %i No projects yet
    - current_user.projects.closed.each do |project|
      %tr
        %td= project.id
        %td= project.name
        %td= render partial: 'projects/status_badge', locals: { record: project }
        %td= project_last_updated_at(project)
        %td= project_edited_at(project)
        %td= project_created_at(project)
        %td
          = link_to 'View', project_path(project), class: 'btn btn-primary btn-sm float-end'